export const siteContent = {
  hero: {
    description:
      "From mountain retreats to coastal escapes, I help buyers and investors discover properties that match both the landscape and their lifestyle.",
  },
  stats: [
    { value: "50+", label: "Clients guided" },
    { value: "12", label: "Years of experience" },
    { value: "24/7", label: "Support availability" },
  ],
  about: {
    bio: "Mark Estrella focuses on elevated property experiences across scenic coastal and hillside locations. The website presents a polished first impression with sample listings, mock location details, and a clear path to inquiry.",
    highlights: [
      "Guidance for buyers seeking scenic retreats and investment homes",
      "Clear communication from consultation to close",
      "Flexible support for local and overseas clients",
    ],
  },
  achievements: [
    { title: "Scenic Property Expertise", description: "Focused on shoreline homes, ridge-top escapes, and lifestyle-driven retreats." },
    { title: "Client-first Approach", description: "Every consultation is tailored around priorities, timing, and long-term value." },
    { title: "Flexible Reach", description: "Support is designed for local buyers and clients seeking a dependable remote partner." },
    { title: "Future-ready Platform", description: "The site is structured for richer posting details, map previews, and additional listings." },
  ],
  services: [
    "Lifestyle property consultation and buyer matching",
    "Seller guidance and listing positioning",
    "Investment support for scenic and resort-style homes",
    "Responsive inquiries and follow-up support",
  ],
};

export const properties = [
  {
    slug: "sunset-residence",
    title: "Sunset Residence",
    type: "Cliffside Villa",
    status: "Available",
    description: "A panoramic cliffside home with sea views, a private terrace, and a calm atmosphere designed for slow mornings and sunset entertaining.",
    bedrooms: 4,
    bathrooms: 3,
    area: "3,200 sq ft",
    location: "Baler, Aurora",
    mapLabel: "Ocean-view ridge road",
    coordinates: "15.7565°N, 121.5598°E",
    lotSize: "1,200 sqm",
    yearBuilt: "2020",
    view: "Ocean sunrise and mountain horizon",
    access: "Private road access with gated entry",
    amenities: ["Infinity pool", "Rooftop lounge", "Smart home controls", "Covered parking"],
  },
  {
    slug: "harbor-terrace",
    title: "Harbor Terrace",
    type: "Seaside Condo",
    status: "New Listing",
    description: "A modern coastal residence with strong rental potential, easy beach access, and a serene open-plan layout.",
    bedrooms: 2,
    bathrooms: 2,
    area: "1,450 sq ft",
    location: "Poro Point, La Union",
    mapLabel: "Harbor promenade",
    coordinates: "16.6100°N, 120.3170°E",
    lotSize: "180 sqm",
    yearBuilt: "2019",
    view: "Harbor and sunset skyline",
    access: "Walkable to the beach and local cafés",
    amenities: ["Balcony lounge", "Fitness room", "24/7 security", "Guest parking"],
  },
  {
    slug: "greenview-estate",
    title: "Greenview Estate",
    type: "Mountain Retreat",
    status: "Featured",
    description: "A welcoming family retreat with wide outdoor areas, cool air, and an easy connection to nature and nearby hilltop views.",
    bedrooms: 5,
    bathrooms: 4,
    area: "4,600 sq ft",
    location: "Tagaytay Highlands",
    mapLabel: "Pine forest loop",
    coordinates: "14.1140°N, 120.9630°E",
    lotSize: "2,800 sqm",
    yearBuilt: "2017",
    view: "Cloud line and pine forest panorama",
    access: "Private driveway with hilltop entry",
    amenities: ["Outdoor fire pit", "Garden pavilion", "Home office", "Guest suite"],
  },
];
